spring.application.name=demo
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/industrial
spring.datasource.username=myappuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=create
